# Generated by Django 3.0.7 on 2020-07-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
