# Generated by Django 3.0.7 on 2020-07-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0003_auto_20200701_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('ST', 'Em Estudo'), ('DV', 'Em Desenvolvimento'), ('HM', 'Em Homologação'), ('DP', 'Implantada')], default='ST', max_length=2),
            preserve_default=False,
        ),
    ]
