# Generated by Django 3.0.7 on 2020-07-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0005_auto_20200702_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='iib_service_number',
            field=models.PositiveIntegerField(blank=True, help_text='Insert IIB Service Number if already available. ', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
    ]
