# Generated by Django 3.0.7 on 2020-07-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0008_auto_20200703_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='domain_rules',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='domain rules'),
        ),
    ]
