# Generated by Django 3.0.7 on 2020-07-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0010_auto_20200705_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='service',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='format',
            field=models.CharField(choices=[('AN', 'Alfanumérico'), ('NB', 'Número'), ('AR', 'Array')], max_length=2, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.CharField(choices=[('RQ', 'Requisição'), ('RP', 'Resposta')], max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('ST', 'Em estudo'), ('DV', 'Em desenvolvimento'), ('HM', 'Em testes'), ('DP', 'Implantado')], max_length=2),
        ),
        migrations.CreateModel(
            name='ParameterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='label')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.Parameter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.Service')),
            ],
            options={
                'verbose_name': 'parameter group',
                'verbose_name_plural': 'parameter groups',
            },
        ),
    ]
