# Generated by Django 3.0.7 on 2020-07-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0012_auto_20200707_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='parameter_group',
        ),
    ]
