# Generated by Django 3.0.7 on 2020-07-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0013_remove_parameter_parameter_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='parameter_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='descriptor.ParameterGroup'),
            preserve_default=False,
        ),
    ]
