# Generated by Django 3.0.7 on 2020-07-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0016_auto_20200707_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='format',
            field=models.CharField(choices=[('AN', 'Alfanumérico'), ('NB', 'Número'), ('AR', 'Array'), ('OB', 'Object')], max_length=2, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='parametergroup',
            name='type',
            field=models.CharField(choices=[('000', 'Requisição'), ('200', 'Response 200 - ok'), ('400', 'Resposta 400 - erro'), ('403', 'Resposta 403 - não permitido'), ('500', 'Resposta 500 - erro de servidor')], max_length=3, verbose_name='parameter type'),
        ),
    ]
