# Generated by Django 3.0.7 on 2020-07-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0017_auto_20200713_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tag',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='tag'),
        ),
    ]
