# Generated by Django 3.0.8 on 2020-07-23 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('descriptor', '0018_service_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('first_signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First_signer', to=settings.AUTH_USER_MODEL)),
                ('second_signer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Second_signer', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.Service')),
            ],
            options={
                'verbose_name': 'parameter',
                'verbose_name_plural': 'parameter',
            },
        ),
    ]
