# Generated by Django 3.0.7 on 2020-07-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0019_tagsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='descriptor.Api'),
        ),
    ]
