# Generated by Django 3.0.7 on 2020-07-29 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0020_auto_20200727_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='parameter_group',
        ),
        migrations.AddField(
            model_name='parameter',
            name='parameter_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_children', to='descriptor.Parameter'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='format',
            field=models.CharField(choices=[('AN', 'Alfanumérico'), ('NB', 'Número'), ('AR', 'Array'), ('OB', 'Objeto')], max_length=2, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='parametergroup',
            name='type',
            field=models.CharField(choices=[('000', 'Requisição'), ('200', 'Resposta 200 - ok'), ('400', 'Resposta 400 - erro'), ('403', 'Resposta 403 - não permitido'), ('500', 'Resposta 500 - erro de servidor')], max_length=3, verbose_name='parameter type'),
        ),
    ]
