# Generated by Django 3.0.7 on 2020-07-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0021_auto_20200729_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='descriptor.Service'),
            preserve_default=False,
        ),
    ]
