# Generated by Django 3.0.7 on 2020-07-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0024_auto_20200729_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='service',
        ),
        migrations.AddField(
            model_name='parameter',
            name='parameter_group',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='descriptor.ParameterGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametergroup',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_groups', to='descriptor.Service'),
        ),
    ]
