# Generated by Django 3.0.7 on 2020-08-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0025_auto_20200729_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsignature',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_signatures', to='descriptor.Service'),
        ),
    ]
