# Generated by Django 3.0.7 on 2020-08-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0026_auto_20200803_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsignature',
            name='signed_at',
        ),
        migrations.AddField(
            model_name='tagsignature',
            name='first_signature_signed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tagsignature',
            name='second_signature_signed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
