version: '3.4'

services:
    mysql:
        container_name: mysql_papiro
        image: 'mysql:5.7'
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: papirodb
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - papiro-network

    django:
        build: .
        command: python manage.py runserver 0.0.0.0:8000 --insecure
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - mysql
        env_file:
            - .env
        restart: always
        networks:
            - papiro-network


volumes:
    db_data: {}

networks:
  papiro-network:
      driver: bridge
      ipam:
          config:
          - subnet: 192.168.2.5/24
